#!/bin/sh

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

# merge in defaults and keymaps

xrdb -merge $HOME/.Xresources
xmodmap $HOME/.Xmodmap

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

session=${1:-dwm}

case $session in
dwm) exec dbus-launch --exit-with-session dwm ;;
i3 | i3wm) exec dbus-launch --exit-with-session i3 ;;
xmonad) exec xmonad ;;
	# No known session, try to run it as command
	#*) exec $1 ;;
esac
